---
- name: Setup Frigate Server
  hosts: all
  tasks:
    - name: Server Setup
      block:
        - name: Update and upgrade apt packages
          apt:
            upgrade: yes
            update_cache: yes
          become: true

        - name : Remove unused dependencies
          apt: autoremove=true
          become: true

        - name : Clean Up the Cache
          apt: autoclean=true
          become: true

        - name: ensure git is installed
          apt:
            name: "{{ packages }}"
            state: latest
          become: true
          vars:
            packages:
              - git
              - curl
              - wget

        - name: Install Docker
          import_role:
            name: geerlingguy.docker

    - name: Compose Stack Setup
      block:
          - name: Create Frigate directory
            ansible.builtin.file:
              path: /frigate
              state: directory
              mode: '0755'

          - name: Deploy Docker Compose template
            template:
              src: "templates/docker-compose.yml.j2"
              dest: "/frigate/docker-compose.yml"
              owner: root
              group: root
              mode: "0644"

    - name: Caddy Setup
      block: 
          - name: Create Caddy directory
            ansible.builtin.file:
              path: /frigate/caddy
              state: directory
              mode: '0755'

          - name: Deploy Caddyfile template
            template:
              src: "templates/Caddyfile.j2"
              dest: "/frigate/Caddyfile"
              owner: root
              group: root
              mode: "0644"

    - name: oauth2-proxy Setup
      block:
          - name: Create oauth2-proxy directory
            ansible.builtin.file:
              path: /frigate/oauth2-proxy
              state: directory
              mode: '0755'

    - name: Frigate Setup
      block:
          - name: Create frigate directory
            ansible.builtin.file:
              path: /frigate/frigate
              state: directory
              mode: '0755'

    - name: Deploy compose Stack
      block:
          - name: Tear down existing services
            community.docker.docker_compose_v2:
              project_src: /frigate
              state: absent

          - name: Create and start services
            community.docker.docker_compose_v2:
              project_src: /frigate
            register: output

          - name: Show results
            ansible.builtin.debug:
              var: output

          - name: Verify that web and db services are running
            ansible.builtin.assert:
              that:
                - web_container.State == 'running'
                - db_container.State == 'running'
            vars:
              web_container: >-
                {{ output.containers | selectattr("Service", "equalto", "web") | first }}
              db_container: >-
                {{ output.containers | selectattr("Service", "equalto", "db") | first }}