- name: Install Docker
  import_role:
    name: geerlingguy.docker

- name: Create Frigate directory
  ansible.builtin.file:
    path: /frigate
    state: directory
    mode: '0755'

- name: Deploy Docker Compose template
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "/frigate/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"