- name: Create neolink directory
  ansible.builtin.file:
    path: "{{ frigate_config_dir }}/neolink"
    state: directory
    mode: '0755'

- name: Copy neolink.toml
  ansible.builtin.copy:
    src: "files/neolink.toml"
    dest: "{{ frigate_config_dir }}/neolink/neolink.toml"
    mode: '0755'