- name: Create oauth2-proxy directory
  ansible.builtin.file:
    path: "{{ frigate_config_dir }}/oauth2-proxy"
    state: directory
    mode: '0755'

- name: Create custom-templates directory
  ansible.builtin.file:
    path: "{{ frigate_config_dir }}/oauth2-proxy/custom-templates"
    state: directory
    mode: '0755'

- name: Copy custom sign in page 
  ansible.builtin.copy:
    src: "files/sign_in.html"
    dest: "{{ frigate_config_dir }}/oauth2-proxy/custom-templates/sign_in.html"
    mode: '0755'

- name: Copy frigate logo for sign in page
  ansible.builtin.copy:
    src: "files/logo.svg"
    dest: "{{ frigate_config_dir }}/oauth2-proxy/custom-templates/logo.svg"
    mode: '0755'

- name: Deploy oauth2-proxy template
  template:
    src: "templates/oauth2-proxy.yml.j2"
    dest: "{{ frigate_config_dir }}/oauth2-proxy/oauth2-proxy.yml"
    mode: "0755"