app:
  mode: events
  api:
    enabled: true
    port: 8000

frigate:
  server: http://frigate:5000
  ignoressl: true
  public_url: https://frigate.trochalakis.com
  headers:
  startup_check:
    attempts: 5
    interval: 30

  webapi:
    enabled: true
    interval: 30

  mqtt: 
    enabled: false
    server: 
    port:
    clientid:
    username: 
    password: 
    topic_prefix: 

  cameras:
    exclude:
      - garage

alerts:  
  general:
    title: Frigate Alert
    nosnap: allow
    snap_bbox: false
    snap_timestamp: false
    snap_crop: false
    max_snap_retry: 10
    notify_once: false
    notify_detections: false
    recheck_delay: 0
    audio_only: allow

  zones:
    unzoned: allow

  labels:
    min_score:
    allow:
     - person
     - dog
     - cat

  discord:
    enabled: false
    webhook: 
    template:

  gotify:
    enabled: false
    server:
    token: 
    ignoressl:
    template:

  mattermost:
    enabled: false
    webhook:
    channel:
    username:
    priority:
    ignoressl:
    headers:
    template:

  ntfy:
    enabled: false
    server:
    topic:
    ignoressl:
    headers:
    template:

  pushover:
    enabled: true
    token: 
    userkey: 
    devices:
    sound:
    priority: 0
    retry:
    expire:
    ttl:
    template:

  signal:
    enabled: false
    server:
    account:
    recipients:
    ignoressl:
    template:

  smtp:
    enabled: false
    server: 
    port: 
    tls: 
    user:
    password:
    recipient:
    template:

  telegram:
    enabled: false
    chatid:
    token:
    template:

  webhook:
    enabled: false
    server: 
    ignoressl:
    method:
    params:
    headers:
    template:


monitor:
  enabled: false
  url: 
  interval: 
  ignoressl:
